spring:
  security:
    user:
      name: username
      password: pass0rd
  messages:
    basename: messages
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cosmos?verifyServerCertificate=false&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: cosmos_user
    password: 1q2w3e4r!!

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    database: mysql
    hibernate:
      format_sql: true
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"

